### content configuration ###
title:       "Haoxiang Ma"
keywords:    "research,  Haoxiang Ma, computer vision, robot learning"
description: ""
source_link: "https://mahaoxiang822.github.io"
baseurl: "/"
google_analytics_key: UA-87133106-1
markdown: kramdown
tracking_id: UA-87133106-1

sass:
    style: compressed
    sass_dir: _sass




